"""Funded projects of Steel Riders Kft. – official texts supplied by the company.
Each text field is a (hu, en) pair. Shown on projektek.html / en/projects.html."""

GRANTS = [
    {
        "id": "ginop-128-2020", "year": 2021,
        "title": ("Steel Riders Kft. fejlesztésének megvalósítása", "Development of Steel Riders Kft."),
        "tag": ("GINOP – kapacitásbővítés", "GINOP – capacity expansion"),
        "facts": [
            (("Projektazonosító", "Project ID"), ("GINOP-1.2.8-20-2020-00594", "GINOP-1.2.8-20-2020-00594")),
            (("Támogatás mértéke", "Aid intensity"), ("68,71%", "68.71%")),
            (("Fizikai befejezés", "Physical completion"), ("2021. augusztus 31.", "31 August 2021")),
        ],
        "lead": ("A projekt fő célja a kapacitásbővülés elérése volt a verpeléti telephelyen, a cég fő tevékenységének, a fémmegmunkálásnak a fejlesztésével.",
                 "The main goal was to expand capacity at the Verpelét site by developing the company’s core activity, metal machining."),
        "items": [("1 db AKIRA SEIKI V4 XP CNC függőleges megmunkálóközpont", "1 × AKIRA SEIKI V4 XP CNC vertical machining centre"),
                  ("1 db FiberSX 4020 lézeregység – jelölés és mikromegmunkálás", "1 × FiberSX 4020 laser unit – marking and micro-machining"),
                  ("1 db kontúrmérő", "1 × contour measuring instrument"),
                  ("1 db kompresszor, 1 db koptatógép", "1 × compressor, 1 × tumbling/deburring machine"),
                  ("4 db Cincoze Box PC", "4 × Cincoze Box PC"),
                  ("A székhelyen meglévő raktárépület szigetelése", "Insulation of the existing warehouse building at the head office")],
        "body": [
            ("A Steel Riders Kft. fő tevékenysége a fémmegmunkálás, jelen projekt keretében is ezt a tevékenységét fejlesztette. A projekt fő célja a kapacitásbővülés elérése volt, a verpeléti telephelyen.",
             "The main activity of Steel Riders Kft. is metal machining, and this project developed that activity. The main goal was to increase capacity at the Verpelét site."),
            ("A projekt megvalósítása során beszerzésre került 1 db AKIRA SEIKI V4 XP CNC függőleges megmunkálóközpont. A megmunkálóközpont a precíz fémmegmunkálást teszi lehetővé, beszerzésére a megnövekedett kapacitásigény miatt volt szükség.",
             "The project purchased an AKIRA SEIKI V4 XP CNC vertical machining centre, which enables precise metal machining and was needed because of increased capacity demand."),
            ("Emellett a precíz munkavégzéshez szükséges FiberSX 4020 lézeregység (1 db) került beszerzésre. A lézer a megbízható és precíz jelöléshez és mikromegmunkáláshoz kompakt szerkezete és sokoldalú beépíthetősége miatt könnyen integrálható volt.",
             "A FiberSX 4020 laser unit was also purchased. Thanks to its compact design and versatile mounting, it was easy to integrate for reliable, precise marking and micro-machining."),
            ("A projekt részét képezte a székhelyen meglévő raktárépület szigetelése is. Emellett 1 db kompresszor, 1 db koptatógép, 1 db kontúrmérő és 4 db Cincoze Box PC beszerzésére volt szükség.",
             "The project also included insulating the existing warehouse at the head office, and purchasing a compressor, a tumbling machine, a contour measuring instrument and four Cincoze Box PCs."),
            ("A beszerzett gépekkel az emberi erőforrást is jobban ki tudja használni a társaság, nőtt a munkavállalók hatékonysága, a hatékony munkavégzés pedig profitnövekedést is eredményez. A fejlesztés eredményeképpen a 2020. áprilisi 48 fős átlagos statisztikai létszám tovább növekedett.",
             "The new machines allow better use of human resources and higher employee efficiency, which in turn increases profit. As a result, the average headcount of 48 in April 2020 increased further."),
            ("A beruházás hozzájárult a társaság piaci helyének további erősítéséhez és a munkavállalók megtartásához, ami fontos az elmaradott régióban elhelyezkedő településen.",
             "The investment strengthened the company’s market position and helped retain employees – important for a municipality in a less developed region."),
        ],
    },
    {
        "id": "napelem-2021", "year": 2021,
        "title": ("Napelemes rendszer telepítése a Steel Riders Kft.-nél", "Solar PV system at Steel Riders Kft."),
        "tag": ("Energetika", "Energy"),
        "facts": [
            (("Támogatás mértéke", "Aid intensity"), ("55,00%", "55.00%")),
            (("Fizikai befejezés", "Physical completion"), ("2021. március 22.", "22 March 2021")),
            (("Teljesítmény", "Capacity"), ("48,96 kWp", "48.96 kWp")),
        ],
        "lead": ("Egyszerű energetikai fejlesztés: 48,96 kWp-s napelemes rendszer telepítése, amely csökkenti a vállalkozás rezsiköltségeit.",
                 "A straightforward energy project: installation of a 48.96 kWp solar PV system that reduces the company’s utility costs."),
        "items": [("144 db JA Solar 340 W(m) napelempanel", "144 × JA Solar 340 W(m) PV panels"),
                  ("2 db Fronius ECO 25.0-3-S (wifi) inverter", "2 × Fronius ECO 25.0-3-S (wifi) inverters"),
                  ("Tartószerkezet a tetőszerkezeti rögzítéshez", "Mounting structure for roof fixing")],
        "body": [
            ("A projekt megvalósítása során egy egyszerű energetikai fejlesztés történt meg, melynek egyetlen műszaki és költségtétele a 48,96 kWp-s napelemes rendszer telepítése.",
             "The project was a simple energy development whose only technical and cost item was the installation of a 48.96 kWp solar PV system."),
            ("A rendszer keretében 144 db JA Solar 340 W(m) panel és 2 db Fronius ECO 25.0-3-S (wifi) inverter került telepítésre, továbbá a tartószerkezet a tetőszerkezeti rögzítéshez.",
             "It comprises 144 JA Solar 340 W(m) panels, two Fronius ECO 25.0-3-S (wifi) inverters and the mounting structure for roof fixing."),
            ("A fejlesztés sikeresen megvalósult, és hozzájárul a vállalkozás rezsiköltségeinek csökkentéséhez.",
             "The development was completed successfully and helps reduce the company’s utility costs."),
        ],
    },
    {
        "id": "irinyi-2020", "year": 2020,
        "title": ("Beszállítói tevékenység fejlesztése az Irinyi Terv keretében", "Supplier development under the Irinyi Plan"),
        "tag": ("Irinyi Terv", "Irinyi Plan"),
        "full": ("Steel Riders Kft. Irinyi Terv keretében kiemelt ágazatban megvalósuló beszállítói tevékenységének fejlesztése",
                 "Development of the supplier activities of Steel Riders Kft. in a priority sector under the Irinyi Plan"),
        "facts": [
            (("Támogatás mértéke", "Aid intensity"), ("50%", "50%")),
            (("Fizikai befejezés", "Physical completion"), ("2020. március 31.", "31 March 2020")),
        ],
        "lead": ("CNC gépbeszerzés és termelésirányítási rendszer fejlesztése a beszállítói tevékenység bővítéséhez – beszállítói együttműködési megállapodással az integrátorral.",
                 "CNC machine purchase and production management system development to grow supplier activities – backed by a supplier cooperation agreement with the integrator."),
        "items": [("2 db STAR SB-20RG CNC hosszeszterga automata", "2 × STAR SB-20RG CNC Swiss-type automatic lathes"),
                  ("Termelésirányítási rendszer fejlesztése és a munkavállalók képzése", "Production management system development and staff training"),
                  ("Meglévő csarnok gépészeti és villamossági fejlesztése", "Mechanical and electrical upgrade of an existing hall"),
                  ("Marketingtevékenység új beszállítói kapcsolatokhoz", "Marketing to build new supplier relationships")],
        "body": [
            ("A projekt keretében megtörtént a növekedés biztosításához elengedhetetlenül szükséges CNC gépbeszerzés, valamint a hatékonyság fokozásához a termelésirányítási rendszer fejlesztése.",
             "The project covered the CNC machine purchase essential for growth and the development of the production management system to increase efficiency."),
            ("A termelésirányítási rendszer használatához a munkavállalók képzésen vettek részt, hogy megfelelő szinten és minél gyorsabban elsajátítsák a rendszer optimális használatához szükséges tudást. A projekt keretében egy már meglévő csarnok gépészeti és villamossági fejlesztése történt meg a gyártó funkció betöltése érdekében. A fejlesztés részét képezte marketingtevékenység is, amely további beszállítói kapcsolatok kiépítését célozza.",
             "Employees were trained to master the production management system quickly and thoroughly. An existing hall received mechanical and electrical upgrades so it could serve as a production area. The project also included marketing aimed at building further supplier relationships."),
            ("Összefoglalva, a projekt célja a vállalkozás beszállítói tevékenységének fejlesztése volt, amelyre beszállítói együttműködési megállapodást kötött az integrátorral. A projekt keretében 2 db STAR SB-20RG típusú CNC hosszeszterga automata került beszerzésre.",
             "In short, the aim was to develop the company’s supplier activities, for which a supplier cooperation agreement was signed with the integrator. Two STAR SB-20RG CNC Swiss-type automatic lathes were purchased."),
        ],
    },
    {
        "id": "helikopter-2018", "year": 2018,
        "title": ("Ultrakönnyű, kétszemélyes, hibrid meghajtású helikopter kifejlesztése", "Development of an ultralight two-seat hybrid-powered helicopter"),
        "tag": ("GINOP – K+F", "GINOP – R&D"),
        "facts": [
            (("Konstrukció", "Scheme"), ("GINOP-2.1.2-8-1-4-16", "GINOP-2.1.2-8-1-4-16")),
            (("Támogatás mértéke", "Aid intensity"), ("55%", "55%")),
            (("Hitel mértéke", "Loan share"), ("27,50%", "27.50%")),
            (("Tervezett befejezés", "Planned completion"), ("2020. szeptember 13.", "13 September 2020")),
        ],
        "lead": ("A Steel Riders Kft. által kifejlesztett Hungaro Copter HC-01 egyszemélyes ultrakönnyű helikopter kétszemélyes, hibrid meghajtású változatának kifejlesztése.",
                 "Development of a two-seat, hybrid-powered version of the Hungaro Copter HC-01 single-seat ultralight helicopter developed by Steel Riders Kft."),
        "items": [("AKIRA SEIKI SR42 XP függőleges megmunkálóközpont", "AKIRA SEIKI SR42 XP vertical machining centre"),
                  ("Infrastrukturális beruházás a gyártás hatékonyságáért", "Infrastructure investment for production efficiency")],
        "link": "hc02",
        "body": [
            ("Jelen projekt célja a Steel Riders Kft. által kifejlesztett Hungaro Copter HC-01 egyszemélyes ultrakönnyű helikopter kétszemélyes, hibrid meghajtású típusának kifejlesztése.",
             "The aim of the project is to develop a two-seat hybrid-powered type of the Hungaro Copter HC-01 single-seat ultralight helicopter developed by Steel Riders Kft."),
            ("A 100%-ban magyar fejlesztésű és gyártású helikoptereket a belföldi és a nemzetközi piacokon tervezzük értékesíteni, ezáltal a hazai repülőipar elismertségét is magasabb szintre tudjuk emelni.",
             "We plan to sell the 100% Hungarian-designed and built helicopters on domestic and international markets, raising the profile of the Hungarian aviation industry."),
            ("A helikopter alapvető és egyedülálló biztonsági jellemzője a hibrid meghajtású mentőrendszer, amely motorleállás esetén biztosítja a biztonságos leszállást.",
             "A fundamental and unique safety feature of the helicopter is its hybrid-powered rescue system, which ensures a safe landing in the event of engine failure."),
            ("A gyártási folyamat hatékonyságának növelését új AKIRA SEIKI SR42 XP típusú függőleges megmunkálóközpont beszerzésével, valamint a tervezett infrastrukturális beruházással kívánjuk támogatni.",
             "Production efficiency is supported by a new AKIRA SEIKI SR42 XP vertical machining centre and the planned infrastructure investment."),
            ("Potenciális vevőink magánszemélyek, üzletemberek és mezőgazdasági vállalkozók köreiből kerülnek ki; emellett a helikopter oktatási, ipari és technikai célú kiszolgálásra is alkalmas lesz.",
             "Potential customers include private individuals, business people and agricultural entrepreneurs; the helicopter will also be suitable for training, industrial and technical services."),
        ],
    },
    {
        "id": "kapacitas-2017", "year": 2017,
        "title": ("Kapacitásbővítő beruházás – 2017", "Capacity expansion investment – 2017"),
        "tag": ("Kapacitásbővítés", "Capacity expansion"),
        "facts": [
            (("Támogatás mértéke", "Aid intensity"), ("49,91%", "49.91%")),
            (("Fizikai befejezés", "Physical completion"), ("2018. február 21.", "21 February 2018")),
        ],
        "lead": ("A verpeléti telephely kapacitásbővítése: bővült a gyártmányok köre, nőtt az árbevétel és az ügyfélkör, a munkahelyek megmaradtak.",
                 "Capacity expansion at the Verpelét site: a wider product range, higher revenue and more customers, with jobs retained."),
        "items": [("1 db STAR SR-32J CNC hosszeszterga automata", "1 × STAR SR-32J CNC Swiss-type automatic lathe"),
                  ("1 db MICRO-3D 8-10-6 CNC koordináta-mérőgép tartozékokkal", "1 × MICRO-3D 8-10-6 CNC coordinate measuring machine with accessories"),
                  ("1 db APE 40 AP ipari fúróélező gép folyadékhűtéssel", "1 × APE 40 AP industrial drill grinder with coolant"),
                  ("1 db ALUP Allegro 23 Plus kompresszor", "1 × ALUP Allegro 23 Plus compressor"),
                  ("1 db 300 l-es napkollektoros berendezés", "1 × 300 l solar thermal system"),
                  ("Autodesk Product Design Collection szoftver", "Autodesk Product Design Collection software"),
                  ("Finomkiesztergáló garnitúra, munkadarab-megfogó egység, szerszámtartó garnitúra", "Fine boring set, workholding unit, tool holder set"),
                  ("Mérőeszközök: digitális külső és analóg belső mikrométerek, mérőhasábok, digitális tolómérők, digitális karos mérőórák", "Gauges: digital outside and analogue inside micrometers, gauge blocks, digital calipers, digital lever dial indicators")],
        "body": [
            ("A fejlesztés célja a Steel Riders Kft. kapacitásbővülésének megvalósítása a verpeléti telephelyen. A fejlesztés eredményeként a meglévő telephelyen előállított gyártmányok köre bővült.",
             "The aim was to expand the capacity of Steel Riders Kft. at the Verpelét site. As a result, the range of products manufactured there has widened."),
            ("A projekt célja a vállalkozás eredményességének fokozása és további megrendelői igények kielégítése. A fejlesztés hatására nő a társaság árbevétele és ügyfélköre, biztosított a meglévő munkavállalók megtartása, és a beruházás további létszámbővülést is eredményezhet.",
             "The project aimed to improve performance and meet further customer demand. It increases revenue and the customer base, secures existing jobs and may lead to further hiring."),
        ],
    },
    {
        "id": "ginop-122-2016", "year": 2016,
        "title": ("Steel Riders Kft. kapacitásbővítő beruházása", "Capacity expansion investment of Steel Riders Kft."),
        "tag": ("GINOP – kapacitásbővítés", "GINOP – capacity expansion"),
        "facts": [
            (("Pályázati azonosító", "Project ID"), ("GINOP-1.2.2-15-2015-01176", "GINOP-1.2.2-15-2015-01176")),
            (("Támogatás összege", "Grant amount"), ("30 113 095 Ft", "HUF 30,113,095")),
            (("Támogatás mértéke", "Aid intensity"), ("50%", "50%")),
            (("Fizikai befejezés", "Physical completion"), ("2016. augusztus 31.", "31 August 2016")),
        ],
        "lead": ("Eszközbeszerzés és infrastrukturális beruházás: csarnokfejlesztés, új CNC eszterga nagyobb alkatrészekhez és képalkotásos profilmérő.",
                 "Equipment and infrastructure investment: hall development, a new CNC lathe for larger parts and an imaging profile measuring system."),
        "items": [("Csarnokfejlesztés", "Production hall development"),
                  ("CNC esztergagép nagyobb méretű alkatrészek gyártásához", "CNC lathe for larger components"),
                  ("Képalkotásos profilmérő – ellenőrzés a gyártás több fázisában", "Imaging profile measuring system – inspection at several production stages")],
        "extra": [(("Tárgy", "Subject"), ("Mikro-, kis- és középvállalkozások kapacitásbővítő beruházásainak támogatása", "Support for capacity expansion investments of micro, small and medium-sized enterprises")),
                  (("Kedvezményezett", "Beneficiary"), ("STEEL RIDERS Kereskedelmi és Szolgáltató Korlátolt Felelősségű Társaság, 3351 Verpelét, Kossuth utca 64.", "STEEL RIDERS Kereskedelmi és Szolgáltató Korlátolt Felelősségű Társaság, Kossuth utca 64, 3351 Verpelét"))],
        "body": [
            ("A Steel Riders Kft. dinamikusan fejlődő társaság, stabil gazdasági háttérrel. Verpeléti székhelyünkön szükségessé vált egy kapacitásbővítő beruházás, amelynek köszönhetően társaságunk képes kielégíteni partnerei növekvő igényeit és nagyobb méretű alkatrészekre vonatkozó szükségleteit. A projekt keretében eszközbeszerzést és infrastrukturális beruházást valósítottunk meg a Gazdaságfejlesztési és Innovációs Operatív Program keretében.",
             "Steel Riders Kft. is a dynamically growing company with a stable financial background. A capacity expansion became necessary at our Verpelét head office so that we can meet our partners’ growing needs, including larger components. Under the Economic Development and Innovation Operational Programme we carried out equipment purchases and an infrastructure investment."),
            ("A piaci igények az egyre jobb minőségű termékek és a szélesebb körű szolgáltatások irányába mutatnak. A beruházás keretében megtörtént a csarnok fejlesztése, amely minden tekintetben képes kiszolgálni termelői tevékenységünket; a megnövekedett kapacitással magasabb színvonalú szolgáltatást nyújthatunk jelenlegi és jövőbeni partnereinknek.",
             "The market demands ever higher quality and broader services. The investment developed the production hall so it fully serves our manufacturing; with the added capacity we can offer a higher level of service to current and future partners."),
            ("A projekt során beszerzésre került egy CNC esztergagép, amelynek köszönhetően nagyobb méretű alkatrészeket is gyártani tudunk, és a megrendeléseket saját gyártásban, bérgyártás és alvállalkozók nélkül készíthetjük el. Beszerzésre került továbbá egy képalkotásos profilmérő, amely a gyártási folyamat több fázisában is ellenőrzi a terméket, így az esetleges hibák azonnal orvosolhatók, a selejt nagyságrendileg csökken – ez önmagában is kapacitásnövekedést jelent.",
             "A CNC lathe was purchased that enables us to make larger parts and to produce orders in-house without subcontracting. We also purchased an imaging profile measuring system that checks products at several stages of production, so defects are corrected immediately and scrap falls by an order of magnitude – itself a gain in capacity."),
            ("A fejlesztés eredményeként szélesíteni tudjuk beszállítói lehetőségeinket; az új gépeknek köszönhetően új beszállítói státuszt is elérhetünk, például teljes mértékben ki tudjuk elégíteni a német Leuka társaság igényeit, és így kiemelt, prémium beszállítóvá válhatunk.",
             "As a result we can broaden our supplier opportunities and reach new supplier status – for example, fully meeting the requirements of the German company Leuka and becoming a key premium supplier."),
        ],
    },
    {
        "id": "csarnok-2013", "year": 2013,
        "title": ("Csarnoképület átalakítása", "Conversion of a hall into a production plant"),
        "tag": ("ÉMOP – telephelyfejlesztés", "ÉMOP – site development"),
        "facts": [
            (("Teljes költség", "Total cost"), ("44 930 580 Ft", "HUF 44,930,580")),
            (("Vissza nem térítendő támogatás", "Non-refundable grant"), ("22 259 459 Ft", "HUF 22,259,459")),
            (("Alapterület", "Floor area"), ("1100 m²", "1,100 m²")),
        ],
        "lead": ("Egy korábban tárolóként használt csarnokból 1100 m²-es termelőüzem lett – a termelési alapterület megduplázódott.",
                 "A former storage hall became a 1,100 m² production plant – doubling our production floor area."),
        "items": [("1100 m²-es gyártócsarnok kialakítása", "Creation of a 1,100 m² production hall"),
                  ("A géppark egy részének áthelyezése az új csarnokba", "Relocation of part of the machine park to the new hall")],
        "body": [
            ("Az Észak-magyarországi Operatív Programban meghirdetett Telephelyfejlesztés című pályázati felhívás keretében egy új, a jelenkor igényeinek mindenben megfelelő üzemcsarnokot hoztunk létre. A projekt során egy korábban tárolóként hasznosított üzemcsarnokot termelőüzemmé alakítottunk, hogy a megnövekedett keresletet megfelelően ki tudjuk szolgálni.",
             "Under the Site Development call of the North Hungary Operational Programme we created a new, fully modern production hall by converting a hall previously used for storage, to meet increased demand."),
            ("Az 1100 m² alapterületű, gyártó funkciójú csarnok kialakításával a termelői alapterület a duplájára nőtt; az új csarnokba a meglévő géppark egy része került áthelyezésre, hogy ott is mihamarabb megindulhasson a termelés. A beruházás eredményeként a termelői kapacitás jelentősen bővült.",
             "With the 1,100 m² production hall our production area doubled; part of the existing machine park was moved in so production could start quickly. Production capacity expanded significantly."),
            ("A beruházás teljes költsége 44 930 580 Ft, amelyhez társaságunk 22 259 459 Ft vissza nem térítendő uniós támogatást nyert el.",
             "The total cost was HUF 44,930,580, towards which we received a non-refundable EU grant of HUF 22,259,459."),
        ],
    },
    {
        "id": "sap-2012", "year": 2012,
        "title": ("Vállalati folyamatmenedzsment támogatása", "Support for business process management"),
        "tag": ("Informatika – SAP", "IT – SAP"),
        "facts": [
            (("Teljes költség", "Total cost"), ("8 688 000 Ft", "HUF 8,688,000")),
            (("Vissza nem térítendő támogatás", "Non-refundable grant"), ("4 344 000 Ft", "HUF 4,344,000")),
        ],
        "lead": ("Átfogó SAP vállalatirányítási rendszer bevezetése: automatizált gyártási és üzleti folyamatok, hatékonyabb értékesítés, reklamációkezelés és logisztika.",
                 "Introduction of a comprehensive SAP ERP system: automated production and business processes, more efficient sales, complaint handling and logistics."),
        "items": [("SAP integrált vállalatirányítási rendszer", "SAP integrated ERP system")],
        "body": [
            ("A megnövekedett gyártási igények elengedhetetlenné tették egy vállalati folyamatmenedzsment-rendszer bevezetését. A magasabb vevői elvárások, a termékek, rendelések és számlázás kezelésére, illetve a belső gyártási folyamatokra az akkori informatikai rendszerünk alkalmatlan volt.",
             "Growing production made a business process management system essential. Our previous IT system could not handle higher customer expectations, products, orders, invoicing or internal production processes."),
            ("A megoldás egy átfogó SAP vállalatirányítási rendszer lett: a belső folyamatok hatékonysága jelentősen javult, a gyártási és egyéb folyamatok automatizálódtak. A fejlesztés javította az értékesítés és a reklamációkezelés hatékonyságát, és segíti a beszerzésben logisztikai feladatokat ellátó munkatársak munkáját.",
             "The solution was a comprehensive SAP ERP system: internal efficiency improved significantly and production and other processes were automated. Sales and complaint handling became more efficient, and purchasing and logistics staff are better supported."),
            ("A beruházás teljes költsége 8 688 000 Ft, amelyhez társaságunk 4 344 000 Ft vissza nem térítendő támogatást nyert el.",
             "The total cost was HUF 8,688,000, towards which we received a non-refundable grant of HUF 4,344,000."),
        ],
    },
]
